"""requirement review snapshots and human decisions"""

import sqlalchemy as sa
from alembic import op

revision = "47db37dd210d"
down_revision = "53991cc65a6e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "requirement_reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("requirement_id", sa.Integer(), nullable=False),
        sa.Column("request_key", sa.String(length=36), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("prompt_version", sa.String(length=40), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("provider", sa.String(length=300), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_code", sa.String(), nullable=False),
        sa.Column("findings", sa.JSON(), nullable=False),
        sa.Column("usage", sa.JSON(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["requirements.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("request_key"),
    )
    with op.batch_alter_table("requirement_reviews", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_requirement_reviews_requirement_id"),
            ["requirement_id"],
            unique=False,
        )

    op.create_table(
        "requirement_revisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("requirement_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["requirements.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("requirement_id", "version"),
    )
    with op.batch_alter_table("requirement_revisions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_requirement_revisions_requirement_id"),
            ["requirement_id"],
            unique=False,
        )

    op.create_table(
        "review_decisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("review_id", sa.Integer(), nullable=False),
        sa.Column("finding_index", sa.Integer(), nullable=False),
        sa.Column("decision", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["requirement_reviews.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("review_id", "finding_index"),
    )
    with op.batch_alter_table("review_decisions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_review_decisions_review_id"), ["review_id"], unique=False
        )

    with op.batch_alter_table("requirements", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "acceptance_criteria", sa.String(), server_default="", nullable=False
            )
        )
        batch_op.add_column(
            sa.Column("version", sa.Integer(), server_default="1", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("requirements", schema=None) as batch_op:
        batch_op.drop_column("version")
        batch_op.drop_column("acceptance_criteria")

    with op.batch_alter_table("review_decisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_review_decisions_review_id"))

    op.drop_table("review_decisions")
    with op.batch_alter_table("requirement_revisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_requirement_revisions_requirement_id"))

    op.drop_table("requirement_revisions")
    with op.batch_alter_table("requirement_reviews", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_requirement_reviews_requirement_id"))

    op.drop_table("requirement_reviews")
    # ### end Alembic commands ###
