"""track CI synchronization coverage"""

import sqlalchemy as sa
from alembic import op

revision = "53991cc65a6e"
down_revision = "c78942c8bb86"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.add_column(sa.Column("ci_synced_at", sa.DateTime(), nullable=True))
        batch_op.add_column(
            sa.Column("ci_sync_note", sa.String(), server_default="", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_column("ci_sync_note")
        batch_op.drop_column("ci_synced_at")

    # ### end Alembic commands ###
