"""initial collaboration schema"""

import sqlalchemy as sa
from alembic import op

revision = "85da8288608d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("repository", sa.String(length=300), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("mode", sa.String(length=10), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("imported_at", sa.DateTime(), nullable=True),
        sa.Column("import_note", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("repository"),
    )
    op.create_table(
        "commits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("sha", sa.String(length=64), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("author", sa.String(length=200), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "sha"),
    )
    with op.batch_alter_table("commits", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_commits_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "pull_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("author", sa.String(length=200), nullable=False),
        sa.Column("labels", sa.JSON(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("first_review_at", sa.DateTime(), nullable=True),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column("merged_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "number"),
    )
    with op.batch_alter_table("pull_requests", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_pull_requests_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "requirements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("change_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("requirements", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_requirements_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "issues",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("requirement_id", sa.Integer(), nullable=True),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("author", sa.String(length=200), nullable=False),
        sa.Column("labels", sa.JSON(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["requirements.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "number"),
    )
    with op.batch_alter_table("issues", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_issues_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "pr_commits",
        sa.Column("pr_id", sa.Integer(), nullable=False),
        sa.Column("commit_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["commit_id"],
            ["commits.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pr_id"],
            ["pull_requests.id"],
        ),
        sa.PrimaryKeyConstraint("pr_id", "commit_id"),
    )
    op.create_table(
        "pr_issues",
        sa.Column("pr_id", sa.Integer(), nullable=False),
        sa.Column("issue_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["issue_id"],
            ["issues.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pr_id"],
            ["pull_requests.id"],
        ),
        sa.PrimaryKeyConstraint("pr_id", "issue_id"),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("requirement_id", sa.Integer(), nullable=True),
        sa.Column("issue_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("task_type", sa.String(length=40), nullable=False),
        sa.Column("estimated_hours", sa.Float(), nullable=False),
        sa.Column("actual_hours", sa.Float(), nullable=True),
        sa.Column("uses_ai", sa.Boolean(), nullable=False),
        sa.Column("rework_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["issue_id"],
            ["issues.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["requirements.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tasks_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "ai_interactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("tool", sa.String(length=100), nullable=False),
        sa.Column("stage", sa.String(length=40), nullable=False),
        sa.Column("purpose", sa.String(length=500), nullable=False),
        sa.Column("prompt_summary", sa.String(length=1000), nullable=False),
        sa.Column("suggestion_summary", sa.String(length=1000), nullable=False),
        sa.Column("prompt_count", sa.Integer(), nullable=False),
        sa.Column("suggestion_count", sa.Integer(), nullable=False),
        sa.Column("accepted_count", sa.Integer(), nullable=False),
        sa.Column("human_modification_count", sa.Integer(), nullable=False),
        sa.Column("modification_notes", sa.String(length=1000), nullable=False),
        sa.Column("estimated_before_hours", sa.Float(), nullable=False),
        sa.Column("actual_hours", sa.Float(), nullable=False),
        sa.Column("quality_result", sa.String(length=500), nullable=False),
        sa.Column("notes", sa.String(length=1000), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ai_interactions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ai_interactions_task_id"), ["task_id"], unique=False
        )

    op.create_table(
        "defects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("defects", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_defects_task_id"), ["task_id"], unique=False
        )

    op.create_table(
        "retrospectives",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("summary", sa.String(length=2000), nullable=False),
        sa.Column("action_item", sa.String(length=1000), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("retrospectives", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_retrospectives_task_id"), ["task_id"], unique=False
        )

    op.create_table(
        "task_commits",
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("commit_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["commit_id"],
            ["commits.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("task_id", "commit_id"),
    )
    op.create_table(
        "task_prs",
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("pr_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pr_id"],
            ["pull_requests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("task_id", "pr_id"),
    )
    op.create_table(
        "test_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("passed", sa.Integer(), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("test_results", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_test_results_task_id"), ["task_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("test_results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_test_results_task_id"))

    op.drop_table("test_results")
    op.drop_table("task_prs")
    op.drop_table("task_commits")
    with op.batch_alter_table("retrospectives", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_retrospectives_task_id"))

    op.drop_table("retrospectives")
    with op.batch_alter_table("defects", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_defects_task_id"))

    op.drop_table("defects")
    with op.batch_alter_table("ai_interactions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ai_interactions_task_id"))

    op.drop_table("ai_interactions")
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tasks_project_id"))

    op.drop_table("tasks")
    op.drop_table("pr_issues")
    op.drop_table("pr_commits")
    with op.batch_alter_table("issues", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_issues_project_id"))

    op.drop_table("issues")
    with op.batch_alter_table("requirements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_requirements_project_id"))

    op.drop_table("requirements")
    with op.batch_alter_table("pull_requests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pull_requests_project_id"))

    op.drop_table("pull_requests")
    with op.batch_alter_table("commits", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_commits_project_id"))

    op.drop_table("commits")
    op.drop_table("projects")
    # ### end Alembic commands ###
