"""add CI run attempts and unique test evidence"""

import sqlalchemy as sa
from alembic import op

revision = "c78942c8bb86"
down_revision = "85da8288608d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ci_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("head_sha", sa.String(length=64), nullable=False),
        sa.Column("branch", sa.String(length=300), nullable=False),
        sa.Column("event", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("conclusion", sa.String(length=30), nullable=True),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("pr_numbers", sa.JSON(), nullable=False),
        sa.Column("jobs", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("synced_at", sa.DateTime(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column("association", sa.String(length=30), nullable=False),
        sa.Column("candidate_task_ids", sa.JSON(), nullable=False),
        sa.Column("evidence_status", sa.String(length=30), nullable=False),
        sa.Column("note", sa.String(), nullable=False),
        sa.Column("artifact_id", sa.BigInteger(), nullable=True),
        sa.Column("digest", sa.String(length=80), nullable=False),
        sa.Column("reports", sa.JSON(), nullable=False),
        sa.Column("passed", sa.Integer(), nullable=True),
        sa.Column("failed", sa.Integer(), nullable=True),
        sa.Column("errors", sa.Integer(), nullable=True),
        sa.Column("skipped", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "run_id", "attempt"),
    )
    with op.batch_alter_table("ci_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ci_runs_head_sha"), ["head_sha"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_ci_runs_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_ci_runs_task_id"), ["task_id"], unique=False
        )

    with op.batch_alter_table("test_results", schema=None) as batch_op:
        batch_op.add_column(sa.Column("ci_run_id", sa.Integer(), nullable=True))
        batch_op.create_unique_constraint("uq_test_results_ci_run_id", ["ci_run_id"])
        batch_op.create_foreign_key(
            "fk_test_results_ci_run_id", "ci_runs", ["ci_run_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("test_results", schema=None) as batch_op:
        batch_op.drop_constraint("fk_test_results_ci_run_id", type_="foreignkey")
        batch_op.drop_constraint("uq_test_results_ci_run_id", type_="unique")
        batch_op.drop_column("ci_run_id")

    with op.batch_alter_table("ci_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ci_runs_task_id"))
        batch_op.drop_index(batch_op.f("ix_ci_runs_project_id"))
        batch_op.drop_index(batch_op.f("ix_ci_runs_head_sha"))

    op.drop_table("ci_runs")
    # ### end Alembic commands ###
